### ISSUE TITLE
Setting nic.strength_warning=10 results in '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by bekoeppel** [tobi-wan-kenobi/bumblebee-status#1028]
#### Description
Affected module: `nic`
Version used: 2.2.0 installed with `pip`

Configuring `nic.strength_warning` results in red error bar with message `'<' not supported between instances of 'int' and 'str' `.

#### How to reproduce

```
bumblebee-status -m nic -p nic.strength_warning=10
{"version": 1, "click_events": true}
[
[2024-12-06 20:20:37,408] bumblebee-status ERROR    '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/usr/local/bin/bumblebee-status", line 152, in <module>
    main()
  File "/usr/local/bin/bumblebee-status", line 142, in main
    core.event.trigger("draw")
  File "/usr/local/lib/python3.12/site-packages/bumblebee_status/core/event.py", line 35, in trigger
    callback()
  File "/usr/local/lib/python3.12/site-packages/bumblebee_status/core/event.py", line 7, in <lambda>
    cb = lambda: callback(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bumblebee_status/core/output.py", line 186, in draw
    data = cb(args) if args else cb()
                                 ^^^^
  File "/usr/local/lib/python3.12/site-packages/bumblebee_status/core/output.py", line 299, in statusline
    blocks.extend(self.blocks(module))
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bumblebee_status/core/output.py", line 261, in blocks
    if "critical" in widget.state() and self.__config.errorhide(widget.module.name):
                     ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bumblebee_status/core/widget.py", line 77, in state
    tmp = self.module.state(self)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bumblebee_status/modules/core/nic.py", line 82, in state
    elif strength < self._strength_threshold_warning:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
[{"full_text": " '<' not supported between instances of 'int' and 'str' ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
```

The same happens if I quote the value: `bumblebee-status -m nic -p nic.strength_warning="10"`

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot for the report, will fix that right away

**Comment by bekoeppel** [comment]
Thank you for your fast response :tada:. I really like the bumblebee status line :-)
