### ISSUE TITLE
error on loading the `datetime` module

### ISSUE THREAD

**Issue by Chinggis6** [tobi-wan-kenobi/bumblebee-status#159]
when loading `datetime` module:

`Error: satus_command process exited unexpectedly (exit 1)`

without loading, everything is fine.

i think `date` and `time` were separate modules in previous releases.

debug log:

    command line parameter datetime.format=%x %X
    trying to read datetime.format from configuration file

**Comment by tobi-wan-kenobi** [comment]
Hi,

1. Can you please run `bumblebee-status -m datetime -p datetime.format="%x %X"` on the commandline and tell me the output?
2. Are you using python3? If so, there was a bug in v1.4.1 that broke the module `datetime` for python3. That's fixed in master and v1.4.2.
3. Which locale are you using? Maybe it's something related to language-specific representation (this information should also be in the debug log)

Thanks for the bug report!

**Comment by tobi-wan-kenobi** [comment]
closing due to inactivity. if the issue persists, please feel free to reopen :-)

**Comment by promptc3** [comment]
Please reopen the issue I'm having the same problem.
I get this error message `Error: status command process exited unexpectedly (exit 2)`
Here is the result of `bumblebee-status -m datetime -p datetime.format="%x %X"`
    [2017-09-01 00:40:51,370] DEBUG    command line parameter datetime.format=%x %X
[2017-09-01 00:40:51,370] DEBUG    trying to read datetime.format from configuration file
[2017-09-01 00:40:51,370] DEBUG    command line parameter datetime.locale=en_US.UTF-8
[2017-09-01 00:40:51,370] DEBUG    trying to read datetime.locale from configuration file
[2017-09-01 00:40:51,370] DEBUG    command line parameter datetime.left-click=None
[2017-09-01 00:40:51,370] DEBUG    trying to read datetime.left-click from configuration file
[2017-09-01 00:40:51,370] DEBUG    command line parameter datetime.middle-click=None
[2017-09-01 00:40:51,370] DEBUG    trying to read datetime.middle-click from configuration file
[2017-09-01 00:40:51,371] DEBUG    command line parameter datetime.right-click=None
[2017-09-01 00:40:51,371] DEBUG    trying to read datetime.right-click from configuration file
[2017-09-01 00:40:51,371] DEBUG    command line parameter datetime.wheel-up=None
[2017-09-01 00:40:51,371] DEBUG    trying to read datetime.wheel-up from configuration file
[2017-09-01 00:40:51,371] DEBUG    command line parameter datetime.wheel-down=None
[2017-09-01 00:40:51,371] DEBUG    trying to read datetime.wheel-down from configuration file
{"click_events": true, "version": 1}
[
[{"min_width": null, "separator": true, "background": null, "full_text": " 09/01/2017 12:40:51 AM ", "instance": "d64c7537-3d03-4d87-80a1-4b3c5fcacdef", "color": "#aabbcc", "name": "datetime", "align": null, "separator_block_width": null}],

**Comment by tobi-wan-kenobi** [comment]
Hi,

@promptc3 from the output, it looks like `datetime` works fine. Can you please put the whole command (as it is in the i3 configuration) into the commandline and run it? It should terminate and give you an error message.

That message would be very useful to narrow down the issue.

Thanks a lot in advance!

**Comment by promptc3** [comment]
Thanks @tobi-wan-kenobi for your help.
This was a mistake from my side and I realised it when I ran the whole command. My command in i3 conf was 
`<path>/bumblebee-status -m cmus battery nic pasink bluetooth -t solarized-powerline datetime` rather it should be
 `<path>/bumblebee-status -m datetime cmus battery nic pasink bluetooth -t solarized-powerline` since datetime is a module.

**Comment by tobi-wan-kenobi** [comment]
Glad to hear that the issue is resolved!

**Comment by evgeniyantipin** [comment]
I get the "Error: status_command process exited unexpectedly (exit 1)" when I try to use either date or time modules. Any other modules work as expected except these two. Python = 3.6.4.

Here is the output of datetime:

```
[e13@Arch ~]$ ~/.config/bumblebee-status/bumblebee-status -m datetime -p datetime.format="%x %X"

Traceback (most recent call last):
  File "/home/e13/.config/bumblebee-status/bumblebee-status", line 74, in <module>
    main()
  File "/home/e13/.config/bumblebee-status/bumblebee-status", line 46, in main
    inp=inp,
  File "/home/e13/.config/bumblebee-status/bumblebee/engine.py", line 143, in __init__
    self.load_modules(config.modules())
  File "/home/e13/.config/bumblebee-status/bumblebee/engine.py", line 198, in load_modules
    mod = self._load_module(module["module"], module["name"])
  File "/home/e13/.config/bumblebee-status/bumblebee/engine.py", line 237, in _load_module
    "config": self._config
  File "/home/e13/.config/bumblebee-status/bumblebee/modules/datetime.py", line 34, in __init__
    lcl = self.parameter("locale", ".".join(locale.getdefaultlocale()))
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by tobi-wan-kenobi** [comment]
Hm, that looks as if `locale.getdefaultlocale()` doesn't return anything for you.
Could you please give me the output of the following commands:
```
$ python
> import locale
> locale.getdefaultlocale()
```

Thanks!

In the meantime, I will commit a change that falls back to a more or less generic default.

**Comment by evgeniyantipin** [comment]
Oh I get it now, turns out I forgot to set my locale. The output was `(None, None)` of course.
Thank you, everything works correctly after setting the locale.

**Comment by tobi-wan-kenobi** [comment]
perfect, thanks!

**Comment by jeremytregunna** [comment]
Just as a footnote to this. I ran into this same problem, and as it turns out my system was lacking an /etc/locale.conf with the locale set properly, yet nothing in this thread led me to believe my locale was set up wrong, since my command line shell scripts set up my locale there. Only discovered this by running the python script as my status command and checking when I logged in, noting it returned `(None, None)` instead of the expected `('en_US', 'UTF-8')`. Hope this is potentially helpful to someone else.

**Comment by Kei0s** [comment]
sir, i am having the same problem the datetime module not working from the above i am getting this
$ python
> import locale
> locale.getdefaultlocale()
Output:
('en_IN', 'ISO8859-1')
Thanks for the help in advance.
if i may ask do i have to manually add en.us_utf-8 in locale.conf or will it work
i am using manjaro 13wm

**Comment by Kei0s** [comment]
Sir, Above problem Solved by writing 
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

in the ~/.profile file

**Comment by tobi-wan-kenobi** [comment]
Glad to hear it! Nevertheless, I will investigate whether this can be made to work also without locale set.

Thanks for the report!
