### ISSUE TITLE
Why we have to satisfy dependency on modules we don't use?

### ISSUE THREAD

**Issue by freed00m** [tobi-wan-kenobi/bumblebee-status#227]
I didn't look into the code to see why the engine import module has to happen, but If I don't have taskw enabled I shouldn't have to get taskw python from random AUR repository, it's not in official arch repos.

```
./bumblebee-status
Traceback (most recent call last):
  File "./bumblebee-status", line 74, in <module>
    main()
  File "./bumblebee-status", line 46, in main
    inp=inp,
  File "/home/frdm/.config/bumblebee-status/bumblebee/engine.py", line 142, in __ini
    self._aliases = self._read_aliases()
  File "/home/frdm/.config/bumblebee-status/bumblebee/engine.py", line 219, in _read
    mod = importlib.import_module("bumblebee.modules.{}".format(module["name"]))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/frdm/.config/bumblebee-status/bumblebee/modules/taskwarrior.py", line
    from taskw import TaskWarrior
ModuleNotFoundError: No module named 'taskw'
```

**Comment by freed00m** [comment]
Can't even install taskw, the one from AUR doesn't work and the taskw installed via pip didn't help neither.

**Comment by tobi-wan-kenobi** [comment]
oh, that is a pretty bad bug. will fix that in the engine, sorry for that!

⁣Sent from TypeApp ​

**Comment by tobi-wan-kenobi** [comment]
Hope this fixes the problem! I thought I had that implemented already, will need to add a unit test for that :)

**Comment by freed00m** [comment]
It works :) thanks.

Btw: any consideration moving to Font Awesome 5?

**Comment by tobi-wan-kenobi** [comment]
Good question, frankly speaking: I'm not aware that anything the tool is doing depends on a specific Font Awesome version, so if you system supports Font Awesome 5, you should be able to use it in your themes.
