### ISSUE TITLE
Bumblebee-status bar crashes using wal-powerline theme

### ISSUE THREAD

**Issue by deltaxflux** [tobi-wan-kenobi/bumblebee-status#263]
Hey,

I have a problem, not modul but theme. I have a problem with wal-powerline theme.

## Steps to reproduce.

**I use the following to show all themes.**
```
bumblebee-status -l themes
```

**Sample output:**
```
default, greyish-powerline, gruvbox, gruvbox-powerline, powerline, sac_red, solarized, solarized-dark-awesome, solarized-powerline, wal-powerline
```

So I tried the wal-powerline theme  but it gave me following trace:
```
Traceback (most recent call last):
  File "/home/deltax/.bumblebee-status/bumblebee-status", line 79, in <module>
    main()
  File "/home/deltax/.bumblebee-status/bumblebee-status", line 41, in main
    theme = bumblebee.theme.Theme(config.theme(), config.iconset())
  File "/home/deltax/.bumblebee-status/bumblebee/theme.py", line 54, in __init__
    self._init(data)
  File "/home/deltax/.bumblebee-status/bumblebee/theme.py", line 87, in _init
    self._merge(self._colorset, self._load_colors(colorset))
  File "/home/deltax/.bumblebee-status/bumblebee/theme.py", line 164, in _load_colors
    return self._load_wal_colors()
  File "/home/deltax/.bumblebee-status/bumblebee/theme.py", line 154, in _load_wal_colors
    with io.open(walfile) as data:
IsADirectoryError: [Errno 21] Is a directory: '/home/deltax/.cache/wal/colors.json'
```

**Note:**
bumblebee-status is located in ~deltax/.bumblebee-status. The error is that I don't have a color.json. 

Regards,
deltax

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks for the bug report, that's not working as intended :(

I'll do two things:

* document pywal support (already done: https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Features)
* log an error in this case and continue

**Comment by deltaxflux** [comment]
Ah sorry, I missed that.

**Comment by deltaxflux** [comment]
No I thought that this was a regular theme like the others :)
