### ISSUE TITLE
Can't make it work with Manjaro i3wm

### ISSUE THREAD

**Issue by SylEleuth** [tobi-wan-kenobi/bumblebee-status#366]
Error: status_command is not executable (exit 126)

Fresh Manjaro installation, after using
>  ~/.config/bumblebee-status/bumblebee-status -m nic disk:root cpu memory battery date time pasink pasource dnf -p root.path=/ time.format="%H:%M CW %V" date.format="%a, %b %d %Y" -t solarized-powerline

in terminal I got this:

> Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eleuth/.config/bumblebee-status/bumblebee/modules/dnf.py", line 22, in get_dnf_info
    res = bumblebee.util.execute("dnf updateinfo")
  File "/home/eleuth/.config/bumblebee-status/bumblebee/util.py", line 25, in execute
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dnf': 'dnf'

Python 3.7 is not mentioned in requirements. Is that might cause problems?

**Comment by rad4day** [comment]
Afaik manjaro uses pacman as a package manager and not dnf. Therefore dnf is not installed on your system and python is complaining that it can't find it.

Replace dnf with pacman or remove it from your command line.

**Comment by SylEleuth** [comment]
Thank You. That helped.
