### ISSUE TITLE
Unsupported locale setting

### ISSUE THREAD

**Issue by Guigui220D** [tobi-wan-kenobi/bumblebee-status#386]
Affected module: datetime.py

Description:
`locale.Error: unsupported locale setting`
The bar crashes when i'ts launching, here's the full error :
`Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 80, in <module>
    main()
  File "/usr/bin/bumblebee-status", line 51, in main
    theme=theme,
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 140, in __init__
    self.load_modules(config.modules())
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 206, in load_modules
    mod = self._load_module(module["module"], module["name"])
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 248, in _load_module
    "config": self._config
  File "/usr/share/bumblebee-status/bumblebee/modules/datetime.py", line 43, in __init__
    locale.setlocale(locale.LC_TIME, lcl.split("en_US.UTF-8"))
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting`

I can't use date, datetime or time.

**Comment by tobi-wan-kenobi** [comment]
Hi,

sorry for the issues! I think you found a problem in the handling of setting the fallback locale, it should be fixed in the above commit. The fact that you arrive at that position, however, still indicates there's something strange in your locale settings. So it's possible you still observe issues.

If you have any further problems, please let me know!

**Comment by Guigui220D** [comment]
Yes, it was effectively a problem on my side too, it now works after re-setting the locale.
Thank you for your fast response :)
