### ISSUE TITLE
Traffic module raises Exception after core/theme changes

### ISSUE THREAD

**Issue by TheEdgeOfRage** [tobi-wan-kenobi/bumblebee-status#406]
#### Summary
Affected module: traffic, core/theme

Description:
The traffic module causes an Exception when I use the code after this commit: 53462d1f0b3e4d97e4ac70bf6700cc102bec212e

It seems to me that this check
```
if self._widget.get("theme.exclude", "") == name:
    return None
```
passes at some point because `name` is equal to `""` causing it to return `None`.

This is the traceback:
```
Traceback (most recent call last):
  File "/home/pavle/.local/share/bumblebee-status/bumblebee-status", line 54, in main
    engine.run()
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/engine.py", line 272, in run
    self.write_output()
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/engine.py", line 287, in write_output
    self._output.draw(widget=widget, module=module, engine=self)
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/output.py", line 128, in draw
    padding = self._theme.padding(widget)
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/theme.py", line 110, in padding
    return self._get(widget, "padding", "")
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/theme.py", line 253, in _get
    value = theme.get(name, value)
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pavle/.local/share/bumblebee-status/bumblebee-status", line 80, in <module>
    main()
  File "/home/pavle/.local/share/bumblebee-status/bumblebee-status", line 74, in main
    output.draw(widget, error)
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/output.py", line 128, in draw
    padding = self._theme.padding(widget)
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/theme.py", line 110, in padding
    return self._get(widget, "padding", "")
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/theme.py", line 244, in _get
    state_themes.append(self._get(widget, state, {}))
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/theme.py", line 262, in _get
    if mod and not mod.parameter("is-unittest"):
  File "/home/pavle/.local/share/bumblebee-status/bumblebee/engine.py", line 114, in parameter
    value = self._config["config"].get(name, default)
TypeError: 'Config' object is not subscriptable
```

#### What is the current behaviour and what is the expected behaviour?
Nicht gut

#### How to reproduce
Here's my status_command line:
```
status_command ~/.local/share/bumblebee-status/bumblebee-status -m \
	traffic \
	nic \
	cpu \
	memory \
	-p engine.workspacewheel=False \
	traffic.hide_down=True \
	traffic.exclude="lo,virbr,docker,vboxnet,veth,br" \
	nic.exclude="lo,virbr,docker,vboxnet,veth,br" \
	-t gruvbox-powerline
```
but even just this is enough to cause a crash:

`status_command ~/.local/share/bumblebee-status/bumblebee-status -m traffic`

#### Expected behavior
Tun gut sein

**Comment by tobi-wan-kenobi** [comment]
Hi @TheEdgeOfRage , welcome back! (and "rofl" at "nicht gut" - great to see somebody learning languages other than programming ones ;) )

Yeah, I can reproduce that. Strange the autotests didn't catch that, will need to investigate that.

**Comment by tobi-wan-kenobi** [comment]
Should be fixed now, many thanks for pointing it out!
