### ISSUE TITLE
Various modules fail - seems like I'm missing some setup step?

### ISSUE THREAD

**Issue by mr-sk** [tobi-wan-kenobi/bumblebee-status#410]
#### Summary
Affected module: nic

Description:
git cloned the repo into ~.i3/ directory. 
Edited my config to include as bar, but fails. 

So trying to run on the command line to see the issues. 

Seems like this should be running in a virtual env or something for all the requirements, but I don't see that as part of the installation instructions. 

#### How to reproduce
```
./bumblebee-status -m nic disk:root cpu memory battery date time pasink pasource dnf -p root.path=/ time.format="%H:%M CW %V" date.format="%a, %b %d %Y" -t solarized-powerline
WARNING:bumblebee.engine:failed to import docker_ps: No module named requests.exceptions
WARNING:bumblebee.engine:failed to import getcrypto: No module named requests
WARNING:bumblebee.engine:failed to import network_traffic: No module named psutil
WARNING:bumblebee.engine:failed to import nic: No module named netifaces
WARNING:bumblebee.engine:failed to import pihole: No module named requests
WARNING:bumblebee.engine:failed to import spaceapi: No module named requests
WARNING:bumblebee.engine:failed to import stock: No module named requests
WARNING:bumblebee.engine:failed to import traffic: No module named psutil
CRITICAL:bumblebee.engine:failed to import nic: No module named netifaces
Traceback (most recent call last):
  File "./bumblebee-status", line 80, in <module>
    main()
  File "./bumblebee-status", line 51, in main
    theme=theme,
  File "/home/sk/.i3/bumblebee-status/bumblebee/engine.py", line 142, in __init__
    self.load_modules(config.modules())
  File "/home/sk/.i3/bumblebee-status/bumblebee/engine.py", line 208, in load_modules
    mod = self._load_module(module["module"], module["name"])
  File "/home/sk/.i3/bumblebee-status/bumblebee/engine.py", line 251, in _load_module
    raise bumblebee.error.ModuleLoadError("unable to load module {}: {}".format(module_name, str(err)))
bumblebee.error.ModuleLoadError: unable to load module nic: No module named netifaces
```

Netifaces is installed:
```
sudo apt-get install python3-netifaces
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-netifaces is already the newest version (0.10.4-1build2).
0 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.

```

#### Expected behavior
That it works.

**Comment by mr-sk** [comment]
So I pip installed netifaces and psutil and that fixed most of my issues. 

Now I'm seeing:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sk/.i3/bumblebee-status/bumblebee/modules/dnf.py", line 22, in get_dnf_info
    res = bumblebee.util.execute("dnf updateinfo")
  File "/home/sk/.i3/bumblebee-status/bumblebee/util.py", line 25, in execute
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by tobi-wan-kenobi** [comment]
Hi,

sorry to read you're having these issues.

All required modules and CLI tools should be documented here: https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules

None of these modules are mandatory, you just need them if you are *using* the module in question.

The core of bumblebee-status itself should not have any external dependencies (python modules and CLI tools), except for i3, of course.

Hope this helps!

**Comment by tobi-wan-kenobi** [comment]
Timeout, please reopen if the issue persists.
