### ISSUE TITLE
battery_all: testing in VM: No such file or directory: '/sys/class/power_supply/

### ISSUE THREAD

**Issue by jayvdb** [tobi-wan-kenobi/bumblebee-status#455]
#### Summary
Affected module: battery_all

The module should fail more gracefully if battery data isnt available, or the test should handle the failure and skip the test with a useful note.

#### Description:
When run in a VM, which doesnt have access to battery, the tests fail with:
```ps
[   11s] ======================================================================
[   11s] ERROR: test_update (tests.test_modules.TestGenericModules)
[   11s] ----------------------------------------------------------------------
[   11s] Traceback (most recent call last):
[   11s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/tests/test_modules.py", line 31, in setUp
[   11s]     self.objects[mod["name"]] = getattr(cls, "Module")(engine, {"config": config})
[   11s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/bumblebee/modules/battery_all.py", line 28, in __init__
[   11s]     for battery in os.listdir('/sys/class/power_supply/'):
[   11s] FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply/'
[   11s] 
[   11s] ======================================================================
[   11s] ERROR: test_widgets (tests.test_modules.TestGenericModules)
[   11s] ----------------------------------------------------------------------
[   11s] Traceback (most recent call last):
[   11s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/tests/test_modules.py", line 31, in setUp
[   11s]     self.objects[mod["name"]] = getattr(cls, "Module")(engine, {"config": config})
[   11s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/bumblebee/modules/battery_all.py", line 28, in __init__
[   11s]     for battery in os.listdir('/sys/class/power_supply/'):
[   11s] FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply/'
```

#### How to reproduce
Probably can be reproduced by running tests in a Docker.

I am running tests in a VM provided by Open Build Service.
i.e. trying to get tests running in https://build.opensuse.org/package/show/X11:windowmanagers/bumblebee-status

**Comment by tobi-wan-kenobi** [comment]
That makes a lot of sense, will look into it!

Thanks for raising this.

**Comment by jayvdb** [comment]
I noticed this module is using `import power`, which isnt documented, originating from 1bd85ce8d , by @martindoublem .  Martin, maybe you can help with this issue?
