### ISSUE TITLE
Allow test suite to run without internet

### ISSUE THREAD

**Issue by jayvdb** [tobi-wan-kenobi/bumblebee-status#456]
### Feature Request
Distro packaging usually involves running a subset of the tests as a smoketest, and the tests are run in a VM without internet to avoid any pollution.

They need some easy way to avoid the tests that require network.
Currently I am disabling the test modules explicitly, but that will break when a new test module is added which needs network.

Or the tests need to have more mocks, or detect the internet has been disappeared and dynamically switch between live and mock tests... ;-)

#### Summary

Currently the test suite fails with
```py
[   11s] ======================================================================
[   11s] FAIL: test_label (tests.modules.test_http_status.TestHttpStatusModule)
[   11s] ----------------------------------------------------------------------
[   11s] Traceback (most recent call last):
[   11s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/tests/modules/test_http_status.py", line 37, in test_label
[   11s]     self.assertEqual(self.module.getOutput(), "example: 200")
[   11s] AssertionError: 'example: UNK != 200' != 'example: 200'
[   11s] - example: UNK != 200
[   11s] ?          -------
[   11s] + example: 200
[   11s] 
[   11s] -------------------- >> begin captured logging << --------------------
[   11s] urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): example.org:80
[   11s] --------------------- >> end captured logging << ---------------------
[   11s] 
[   11s] ======================================================================
[   11s] FAIL: test_status_error (tests.modules.test_http_status.TestHttpStatusModule)
[   11s] ----------------------------------------------------------------------
[   11s] Traceback (most recent call last):
[   11s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/tests/modules/test_http_status.py", line 26, in test_status_error
[   11s]     self.assertTrue(not "warning" in self.module.state(self.module.widgets()[0]))
[   11s] AssertionError: False is not true
[   11s] -------------------- >> begin captured logging << --------------------
[   11s] urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): example.org:80
[   11s] --------------------- >> end captured logging << ---------------------
[   11s] 
[   11s] ======================================================================
[   11s] FAIL: test_status_success (tests.modules.test_http_status.TestHttpStatusModule)
[   11s] ----------------------------------------------------------------------
[   11s] Traceback (most recent call last):
[   11s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/tests/modules/test_http_status.py", line 15, in test_status_success
[   11s]     self.assertTrue(not "warning" in self.module.state(self.module.widgets()[0]))
[   11s] AssertionError: False is not true
[   11s] -------------------- >> begin captured logging << --------------------
[   11s] urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): example.org:80
[   11s] --------------------- >> end captured logging << ---------------------
```

There is also a noisy module dumping the following into the nose output, but the test isnt failing.
```py
[   20s] During handling of the above exception, another exception occurred:
[   20s] 
[   20s] Traceback (most recent call last):
[   20s]   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
[   20s]     timeout=timeout
[   20s]   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
[   20s]     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
[   20s]   File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
[   20s]     raise MaxRetryError(_pool, url, error or ResponseError(cause))
[   20s] urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='club.entropia.de', port=80): Max retries exceeded with url: /spaceapi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9bab09e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[   20s] 
[   20s] During handling of the above exception, another exception occurred:
[   20s] 
[   20s] Traceback (most recent call last):
[   20s]   File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
[   20s]     self.run()
[   20s]   File "/usr/lib64/python3.7/threading.py", line 865, in run
[   20s]     self._target(*self._args, **self._kwargs)
[   20s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/bumblebee/modules/spaceapi.py", line 117, in get_api_async
[   20s]     with requests.get(self._url, timeout=10) as request:
[   20s]   File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
[   20s]     return request('get', url, params=params, **kwargs)
[   20s]   File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
[   20s]     return session.request(method=method, url=url, **kwargs)
[   20s]   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
[   20s]     resp = self.send(prep, **send_kwargs)
[   20s]   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
[   20s]     r = adapter.send(request, **kwargs)
[   20s]   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in [   20s] During handling of the above exception, another exception occurred:
[   20s] 
[   20s] Traceback (most recent call last):
[   20s]   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
[   20s]     timeout=timeout
[   20s]   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
[   20s]     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
[   20s]   File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
[   20s]     raise MaxRetryError(_pool, url, error or ResponseError(cause))
[   20s] urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='club.entropia.de', port=80): Max retries exceeded with url: /spaceapi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9bab09e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[   20s] 
[   20s] During handling of the above exception, another exception occurred:
[   20s] 
[   20s] Traceback (most recent call last):
[   20s]   File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
[   20s]     self.run()
[   20s]   File "/usr/lib64/python3.7/threading.py", line 865, in run
[   20s]     self._target(*self._args, **self._kwargs)
[   20s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/bumblebee/modules/spaceapi.py", line 117, in get_api_async
[   20s]     with requests.get(self._url, timeout=10) as request:
[   20s]   File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
[   20s]     return request('get', url, params=params, **kwargs)
[   20s]   File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
[   20s]     return session.request(method=method, url=url, **kwargs)
[   20s]   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
[   20s]     resp = self.send(prep, **send_kwargs)
[   20s]   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
[   20s]     r = adapter.send(request, **kwargs)
[   20s]   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
[   20s]     raise ConnectionError(e, request=request)
[   20s] requests.exceptions.ConnectionError: HTTPConnectionPool(host='club.entropia.de', port=80): Max retries exceeded with url: /spaceapi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9bab09e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
send
[   20s]     raise ConnectionError(e, request=request)
[   20s] requests.exceptions.ConnectionError: HTTPConnectionPool(host='club.entropia.de', port=80): Max retries exceeded with url: /spaceapi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9bab09e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by tobi-wan-kenobi** [comment]
Interesting! I'll think about that, on first glance, that might be quite a piece of work to get done correctly.

Just out of curiosity: Which distro are you talking about?

**Comment by jayvdb** [comment]
openSUSE.

**Comment by jayvdb** [comment]
It is quite easy to disable `test_http_status`, so this isnt a high priority.

However making those spaceapi exceptions quieter would be helpful, as they break up an otherwise lovely long line of dots out of nose.  I'm tempted to disable the relevant tests just to not have a mess in the logs

**Comment by jayvdb** [comment]
Oddly, some more fail occasionally

```py
[   47s] ======================================================================
[   47s] ERROR: test_update (tests.test_modules.TestGenericModules)
[   47s] ----------------------------------------------------------------------
[   47s] Traceback (most recent call last):
[   47s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/tests/test_modules.py", line 55, in test_update
[   47s]     self.test_widgets()
[   47s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/tests/test_modules.py", line 49, in test_widgets
[   47s]     self.assertTrue(isinstance(widget.full_text(), str) or isinstance(widget.full_text(), unicode))
[   47s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/bumblebee/output.py", line 96, in full_text
[   47s]     return self._full_text(self)
[   47s]   File "/home/abuild/rpmbuild/BUILD/bumblebee-status-1.9.0/bumblebee/modules/sensors2.py", line 141, in _cpu
[   47s]     mhz = int(m.group(1))
[   47s] AttributeError: 'NoneType' object has no attribute 'group'
[   47s] -------------------- >> begin captured logging << --------------------
[   47s] bumblebee.modules.sensors: DEBUG: Sensors command available
[   47s] urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): ipinfo.io:80
[   47s] --------------------- >> end captured logging << ---------------------
```

**Comment by tobi-wan-kenobi** [comment]
should be fixed in latest master
