### ISSUE TITLE
layout* modules miss config options

### ISSUE THREAD

**Issue by JohnDowson** [tobi-wan-kenobi/bumblebee-status#526]
layout-xkb seems to have been removed, layout doesn't display changes in layout and neither layout nor layout-xkbswitch support 
```
layout.show_variant=false
```
that layout-xkb had.

If I recall correctly, I added that feature, but I don't have the time right now to add it to other layout* modules.

**Comment by somospocos** [comment]
> layout-xkb seems to have been removed

I don't understand, the module is in the repository.

> neither layout nor layout-xkbswitch support layout.show_variant=false that layout-xkb had.

I don't think that the xkb-switch tool that layout-xkbswitch module is using, supports variants at all, I couldn't find anything related by reading `xkb-switch -h`

**Comment by tobi-wan-kenobi** [comment]
I agree with @somospocos , `layout-xkb` should still be available (I rarely remove existing modules). If you let me know the issue you have, I can investigate further.

I'll close the ticket for now, please feel free to reopen it, if the answer @somospocos gave isn't what you are looking for.

Thanks!

**Comment by JohnDowson** [comment]
> I don't understand, the module is in the repository.
It doesn't show up in ```-l modules```
> I don't think that the xkb-switch tool that layout-xkbswitch module is using, supports variants at all, I couldn't find anything related by reading `xkb-switch -h`
then what is ![this](https://i.imgur.com/A9o8NVF.png) ?

**Comment by JohnDowson** [comment]
Okay, it exists as a file, but enabling it throws an error:

```
Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 80, in <module>
    main()
  File "/usr/bin/bumblebee-status", line 47, in main
    engine = bumblebee.engine.Engine(
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 152, in __init__
    self.load_modules(config.modules())
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 221, in load_modules
    mod = self._load_module(module["module"], module["name"])
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 259, in _load_module
    module = importlib.import_module("bumblebee.modules.{}".format(module_name))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/bumblebee-status/bumblebee/modules/layout-xkb.py", line 21, in <module>
    from xkbgroup import *
  File "/home/johnd/.local/lib/python3.8/site-packages/xkbgroup/__init__.py", line 14, in <module>
    from .core import XKeyboard, X11Error
  File "/home/johnd/.local/lib/python3.8/site-packages/xkbgroup/core.py", line 31, in <module>
    from .xkb import *
  File "/home/johnd/.local/lib/python3.8/site-packages/xkbgroup/xkb.py", line 3372, in <module>
    XEHeadOfExtensionList.argtypes = [XEDataObject]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.
```

Which seems like a problem with xkbgroup?

**Comment by tobi-wan-kenobi** [comment]
Yes, that does look like a problem in xkbgroup. Could you try updating the module, please?

**Comment by JohnDowson** [comment]
It persists both on my personal branch and with freshly pulled master.
And xkbgroup itself throws the same error:

```
johnd@workpc ~/bumblebee-status λxkbgroup get
Traceback (most recent call last):
  File "/usr/bin/xkbgroup", line 5, in <module>
    from xkbgroup.__main__ import main
  File "/usr/lib/python3.8/site-packages/xkbgroup/__init__.py", line 14, in <module>
    from .core import XKeyboard, X11Error
  File "/usr/lib/python3.8/site-packages/xkbgroup/core.py", line 31, in <module>
    from .xkb import *
  File "/usr/lib/python3.8/site-packages/xkbgroup/xkb.py", line 3372, in <module>
    XEHeadOfExtensionList.argtypes = [XEDataObject]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.
```
