### ISSUE TITLE
battery-upower stopped working

### ISSUE THREAD

**Issue by tehgibbo** [tobi-wan-kenobi/bumblebee-status#555]
#### Summary
Affected module: battery-upower

#### Description:
crashes the bar when enabled

#### How to reproduce
Pulled the latest GIT 
then 

$ ./bumblebee-status -d -m battery-upower
{"version": 1, "click_events": true}
[
[],
Traceback (most recent call last):
  File "./bumblebee-status", line 54, in main
    engine.run()
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/engine.py", line 285, in run
    self.write_output()
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/engine.py", line 307, in write_output
    self._output.draw(widget=widget, module=module, engine=self)
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/output.py", line 494, in draw
    self._widgets.extend(widget_drawer.draw(widget, module, engine))
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/output.py", line 429, in draw
    separator = self._theme.separator(widget)
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/theme.py", line 165, in separator
    return self._get(widget, "separator", None)
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/theme.py", line 261, in _get
    states = widget.state()
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/output.py", line 307, in state
    states = self._module.state(self)
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/modules/battery-upower.py", line 244, in state
    if capacity < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bumblebee-status", line 80, in <module>
    main()
  File "./bumblebee-status", line 74, in main
    output.draw(widget, error)
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/output.py", line 494, in draw
    self._widgets.extend(widget_drawer.draw(widget, module, engine))
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/output.py", line 429, in draw
    separator = self._theme.separator(widget)
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/theme.py", line 165, in separator
    return self._get(widget, "separator", None)
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/theme.py", line 265, in _get
    state_themes.append(self._get(widget, state, {}))
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/theme.py", line 283, in _get
    if mod and not mod.parameter("is-unittest"):
  File "/home/cilnnot/GIT-apps/bumblebee-status/bumblebee/engine.py", line 123, in parameter
    value = self._config["config"].get(module_name, default)
TypeError: 'Config' object is not subscriptable

**Comment by tobi-wan-kenobi** [comment]
Thanks for raising this. I hope this fixes your issue.

Cheers!

**Comment by tehgibbo** [comment]
Pulled the commit and all seems to be well now. Thanks
