### ISSUE TITLE
Archlinux error modules

### ISSUE THREAD

**Issue by svj666** [tobi-wan-kenobi/bumblebee-status#763]
Command :  ~/.config/bumblebee-status/bumblebee-status -m cpu datetime memory brightness battery -p time.format="%H:%M CW %V" -t solarized

ERROR :

Traceback (most recent call last):
  File "/usr/bin/bumblebee-status/bumblebee-status", line 17, in <module>
    import core.config
  File "/usr/bin/bumblebee-status/bumblebee_status/core/config.py", line 17, in <module>
    import modules.core
ModuleNotFoundError: No module named 'modules.core'

i3 config 
status_command ~/.config/bumblebee-status/bumblebee-status \
     -m cpu datetime memory brightness battery \
     -p time.format="%H:%M" \
     -t solarized

i3status ERROR : status_command process exited unexpectedly (exit1)

**Comment by svj666** [comment]
to solve move bumblebee-status in /bumblebee_statu
and start it or link it in i3config from that PATH
alternatively it is possible to import from the correct core folder by inserting the correct PATH of the modules in the bumblebee-status source.... apparently __init__.py is not enough

**Comment by tobi-wan-kenobi** [comment]
@svj666 which version were you using? the aur package, or maybe the aur-git package? any way, i want to properly fix the issue in the package :)

thanks a lot for the report!

**Comment by svj666** [comment]
no i got this problem directly from git. I use archlinux and python3

**Comment by svj666** [comment]
no i got this problem directly from git. I use archlinux and python3
however the above mentioned solution is valid even if and could rewrite the PATH for "core" because it could not fetch the modules some times. now I don't know why it happens because I tried to run it on archolinux distro D and it didn't present any problems but in my archlinux yes

**Comment by tobi-wan-kenobi** [comment]
That is very strange. I use bumblebee-status from git as well.

In the traceback you posted above, it references "/usr/bin/bumblebee-status/bumblebee-status" - is it possible you have an AUR package installed as well? Or did you symlink it there?

**Comment by bgergely0** [comment]
I have the same issue. It worked for a while, than randomly stopped working. I uninstalled, and reinstalled the aur package,  then the aur-git one as well, but neither seems to work.

**Comment by tobi-wan-kenobi** [comment]
will investigate, thanks for the report!

**Comment by tobi-wan-kenobi** [comment]
@bgergely0 Can you please paste the exact command you enter and the error you get?

I just tried the AUR on an Arch Linux, and it worked for me :(

**Comment by bgergely0** [comment]
Sure!
I'm actually running manjaro, but I don't think that should make a difference.
This is my bar config:
```
bar {
         status_command bumblebee-status -m  playerctl cpu memory battery date time pasink pasource nic uptime \
         -p cpu.format="{:3.1f}%" memory.format="{used} ({percent:2.0f}%)" time.format="%H:%    M" nic.states="^down" nic.format="{state} {ssid}"  -t iceberg-dark-powerline
         position top
         font pango: DejaVu Sans Mono, Font Awesome 10
 } 
```

The error I get when writing `bumblebee-status` in terminal:
```
Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 17, in <module>
    import core.config
  File "/usr/share/bumblebee-status/bumblebee_status/core/config.py", line 17, in <module>
    import modules.core
ModuleNotFoundError: No module named 'modules.core'
```
(If I run it with the parameters defined above, I get the same.)

**Comment by svj666** [comment]
As I said, it is very strange. I am referring to the git package (git clone link) on my distro arcolinuz it works perfectly with no errors in the core module while on archlinux I get the error. I think python centers but the versions are the same. As I said to temporarily resolve it is necessary to move "bumblebee-status" to folder "bumblebbe_status" at this point remove the following parameters from the "bumble-status" source: 

import bumblebee_status.discover

bumblebee_status.discover.discover()

however the reason for the problem is in the call shown in traceback

File "/usr/bin/bumblebee-status/bumblebee_status/core/config.py", line 17, in
import modules.core
ModuleNotFoundError: No module named 'modules.core'

**Comment by tobi-wan-kenobi** [comment]
@svj666 @bgergely0 I tried to reproduce this now, very carefully: I set up an Arch Linux Docker instance and installed the bare minimum to get bumblebee-status running (git clone and makepkg -sicr) - and starting bumblebee-status that way works.

I think the most likely reason is that some other Python module you have on your system is interfering with the namespace of bumblebee, but I am not sure how to troubleshoot that :(

As a poor man's workaround, you could just clone bumblebee-status from git and use that. Sorry for the inconvenience, I will try to think of a better/cleaner solution.
