### ISSUE TITLE
Spotify module writes large amounts of logs to ~/.xsession-errors if spotify is not running

### ISSUE THREAD

**Issue by LokiLuciferase** [tobi-wan-kenobi/bumblebee-status#839]
#### Description
Affected module: spotify
Version used: latest git
Distro/Kernel: Linux Mint 20.2, 5.11.0-43
i3 version: i3-gaps 4.19.1

Hi,

First I'd like to say thank you for this awesome piece of software, I really enjoy having a well-designed hackable status bar written in python.

Secondly, I have been experiencing the following issue:
On my system, the spotify module writes about 2kb/sec of logs to ~/.xsession-errors (which is obviously unsustainable).

These logs have the following shape:

```
...
[2021-12-28 00:37:02,192] spotify          ERROR    org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
Traceback (most recent call last):
  File "/home/testuser/.local/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/home/testuser/.local/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/home/testuser/.local/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.mpris.MediaPlayer2.spotify': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/testuser/.local/lib/python3.9/site-packages/bumblebee_status/modules/contrib/spotify.py", line 134, in update
    self.__get_song()
  File "/home/testuser/.local/lib/python3.9/site-packages/bumblebee_status/modules/contrib/spotify.py", line 120, in __get_song
    spotify = bus.get_object(
  File "/home/testuser/.local/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/home/testuser/.local/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/home/testuser/.local/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/home/testuser/.local/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/home/testuser/.local/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
...
```

#### How to reproduce

1. Add the `spotify` module to your active modules
2. reload i3
3. if spotify is open, close it
3. error logs should now start to be written at a high rate to ~/.xsession-errors. 

#### How to fix
This behaviour is due to the following log call which logs each time the retrieval of song information (rightfully) fails when spotify is off:
https://github.com/tobi-wan-kenobi/bumblebee-status/blob/e590a3cf3f992f78d857cac603da4f29d7f05f3d/bumblebee_status/modules/contrib/spotify.py#L162

After removing this line in my personal fork, the issue is resolved. I would be happy to submit a pull request if this is desired.

**Comment by tobi-wan-kenobi** [comment]
Ouch!

Thanks for the report,I would definitely welcome a PR a lot and immediately merge it :)

Also, many thanks for the kind words!
