### ISSUE TITLE
`Could not parse JSON` error on boot, resolves after i3 refresh

### ISSUE THREAD

**Issue by Dale-Muccignat** [tobi-wan-kenobi/bumblebee-status#940]
#### Description
Affected module: All
Version used: AUR

<description>
On first boot I get this error displayed in the i3 bar:

![captures_126](https://user-images.githubusercontent.com/14990150/203436925-3963c116-b334-4e58-92c1-d77da6972dce.png)

After I reload i3 everything works as expected, it only happens just after I start the computer

#### How to reproduce

Config File used:
```
[core]
modules=spotify,sensors2,cpu,memory,disk,datetime,pulseout,dunst
autohide=cpu,memory,disk,sensors2
theme=custom-powerline

[module-parameters]
disk.format={left}
memory.format={percent:05.02f}%
cpu.format={:05.02f}%
datetime.format=%d/%m/%y %H:%M
cpu.percpu=true
sensors2.chip_include=coretemp, acpitz
sensors2.showcpu=false
sensors2.showname=true
spotify.format={artist}-{title}
```

Theme file used:
```
{
    "icons": [ "awesome-fonts" ],
    "colors": [{
        "red": "#BF616A",
        "orange": "#D08770",
        "yellow": "#EBCB8B",
        "green": "#A3BE8C"
    }],
    "defaults": {
        "warning": {
            "fg": "#2E3440",
            "bg": "#D08770"
        },
        "critical": {
            "fg": "#2E3440",
            "bg": "#BF616A"
        },
		"separator-block-width": 0
    },
    "cycle": [
        { "fg": "#D4E4F1", "bg": "#260273"},
        { "fg": "#D4E4F1", "bg": "#150140"}
    ],
    "dnf": {
        "good": {
            "fg": "#A3BE8C",
            "bg": "#2E3440"
        }
    },
    "apt": {
        "good": {
            "fg": "#A3BE8C",
            "bg": "#2E3440"
        }
    },
    "pacman": {
        "good": {
            "fg": "#A3BE8C",
            "bg": "#2E3440"
        }
    },
    "battery": {
        "charged": {
            "fg": "#2E3440",
            "bg": "#A3BE8C"
        },
        "charging": {
            "fg": "#2E3440",
            "bg": "#81A1C1"
        }
    },
    "pomodoro": {
        "paused": {
            "fg": "#2E3440",
            "bg": "#D08770"
        },
        "work": {
            "fg": "#2E3440",
            "bg": "#EBCB8B"
        },
        "break": {
            "fg": "#A3BE8C",
            "bg": "#2E3440"
        }
    }

}
```

i3 bar command:
```
bar {
    status_command bumblebee-status
    font pango:DejaVu Sans Mono, FontAwesome 10
    tray_output primary
    tray_padding 4
    #mode hide
    colors {
        background #090126
        focused_workspace #EFB893 #EFB893 #150140
        active_workspace #260273 #260273 #ffffff
        inactive_workspace #150140 #150140 #ffffff
    }
}
```

**Comment by tobi-wan-kenobi** [comment]
If possible, it would be great if you could create a debug log (-d -f <path to logfile>) & provide it here in the ticket.

*Maybe* it is related to pulseaudio, in which case it would be an option to add the "autostart" parameter to the pulseaudio module.

Also: Sorry for my long response time!

**Comment by Dale-Muccignat** [comment]
Thanks for the response, I can try trail and error a bit removing those modules and also checking out the autostart. No worries with response time I'm happy!

Here is the log:
```
[2022-11-25 00:22:10,949] input            DEBUG    registering callback ::wheel-up
[2022-11-25 00:22:10,950] input            DEBUG    registering callback ::wheel-down
[2022-11-25 00:22:10,952] module           DEBUG    importing debug from core
[2022-11-25 00:22:10,952] module           WARNING  failed to import spotify from core: No module named 'modules.core.spotify'
[2022-11-25 00:22:10,959] module           DEBUG    importing spotify from contrib
[2022-11-25 00:22:10,960] input            DEBUG    registering callback spotify::1::left-mouse
[2022-11-25 00:22:10,960] input            DEBUG    registering callback spotify::2::left-mouse
[2022-11-25 00:22:10,960] input            DEBUG    registering callback spotify::3::left-mouse
[2022-11-25 00:22:10,962] module           DEBUG    importing sensors2 from core
[2022-11-25 00:22:10,963] cli              DEBUG    sensors -u 
[2022-11-25 00:22:10,981] cli              DEBUG    coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 53.000
  temp1_max: 85.000
  temp1_crit: 105.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 50.000
  temp2_max: 85.000
  temp2_crit: 105.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 49.000
  temp3_max: 85.000
  temp3_crit: 105.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 50.000
  temp4_max: 85.000
  temp4_crit: 105.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 53.000
  temp5_max: 85.000
  temp5_crit: 105.000
  temp5_crit_alarm: 0.000

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 27.800
  temp1_crit: 106.000
temp2:
  temp2_input: 29.800
  temp2_crit: 106.000

amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:
  in0_input: 1.087
fan1:
  fan1_input: 3.000
  fan1_min: 0.000
  fan1_max: 3500.000
edge:
  temp1_input: 49.000
  temp1_crit: 94.000
  temp1_crit_hyst: -273.150
PPT:
  power1_average: 30.249
  power1_cap: 145.000


[2022-11-25 00:22:11,027] module           DEBUG    importing cpu from core
[2022-11-25 00:22:11,027] input            DEBUG    registering callback cpu::left-mouse
[2022-11-25 00:22:11,038] module           DEBUG    importing memory from core
[2022-11-25 00:22:11,038] input            DEBUG    registering callback memory::left-mouse
[2022-11-25 00:22:11,039] module           DEBUG    importing disk from core
[2022-11-25 00:22:11,039] input            DEBUG    registering callback disk::left-mouse
[2022-11-25 00:22:11,047] module           DEBUG    importing datetime from core
[2022-11-25 00:22:11,054] input            DEBUG    registering callback datetime::left-mouse
[2022-11-25 00:22:11,153] module           DEBUG    importing pulseout from core
[2022-11-25 00:22:11,154] input            DEBUG    registering callback pulseout::left-mouse
[2022-11-25 00:22:11,154] input            DEBUG    registering callback pulseout::wheel-up
[2022-11-25 00:22:11,154] input            DEBUG    registering callback pulseout::wheel-down
```

**Comment by tobi-wan-kenobi** [comment]
Weird, that looks good & contains no errors :( Did the error show up when you were running this?

Are you using the AUR -git or the last released version?

**Comment by Dale-Muccignat** [comment]
`pulseout.autostart=true` also doesn't work. I'll double check the log file...

**Comment by Dale-Muccignat** [comment]
If you like error's changing, if not resolving... now with the autostart reloading i3 does not resolve the error. Here is a log file in which I reload i3 a few times
```
[2022-11-25 00:44:12,071] input            DEBUG    registering callback ::wheel-up
[2022-11-25 00:44:12,071] input            DEBUG    registering callback ::wheel-down
[2022-11-25 00:44:12,072] module           DEBUG    importing debug from core
[2022-11-25 00:44:12,073] module           WARNING  failed to import spotify from core: No module named 'modules.core.spotify'
[2022-11-25 00:44:12,081] module           DEBUG    importing spotify from contrib
[2022-11-25 00:44:12,081] input            DEBUG    registering callback spotify::1::left-mouse
[2022-11-25 00:44:12,081] input            DEBUG    registering callback spotify::2::left-mouse
[2022-11-25 00:44:12,082] input            DEBUG    registering callback spotify::3::left-mouse
[2022-11-25 00:44:12,084] module           DEBUG    importing sensors2 from core
[2022-11-25 00:44:12,084] cli              DEBUG    sensors -u 
[2022-11-25 00:44:12,089] cli              DEBUG    coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 53.000
  temp1_max: 85.000
  temp1_crit: 105.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 52.000
  temp2_max: 85.000
  temp2_crit: 105.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 51.000
  temp3_max: 85.000
  temp3_crit: 105.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 52.000
  temp4_max: 85.000
  temp4_crit: 105.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 53.000
  temp5_max: 85.000
  temp5_crit: 105.000
  temp5_crit_alarm: 0.000

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 27.800
  temp1_crit: 106.000
temp2:
  temp2_input: 29.800
  temp2_crit: 106.000

amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:
  in0_input: 1.087
fan1:
  fan1_input: 581.000
  fan1_min: 0.000
  fan1_max: 3500.000
edge:
  temp1_input: 49.000
  temp1_crit: 94.000
  temp1_crit_hyst: -273.150
PPT:
  power1_average: 29.101
  power1_cap: 145.000


[2022-11-25 00:44:12,111] module           DEBUG    importing cpu from core
[2022-11-25 00:44:12,111] input            DEBUG    registering callback cpu::left-mouse
[2022-11-25 00:44:12,112] module           DEBUG    importing memory from core
[2022-11-25 00:44:12,112] input            DEBUG    registering callback memory::left-mouse
[2022-11-25 00:44:12,113] module           DEBUG    importing disk from core
[2022-11-25 00:44:12,113] input            DEBUG    registering callback disk::left-mouse
[2022-11-25 00:44:12,116] module           DEBUG    importing datetime from core
[2022-11-25 00:44:12,116] input            DEBUG    registering callback datetime::left-mouse
[2022-11-25 00:44:12,116] module           WARNING  failed to import arandr from core: No module named 'modules.core.arandr'
[2022-11-25 00:44:12,157] module           DEBUG    importing arandr from contrib
[2022-11-25 00:44:12,157] input            DEBUG    registering callback arandr::left-mouse
[2022-11-25 00:44:12,157] input            DEBUG    registering callback arandr::right-mouse
[2022-11-25 00:44:12,157] module           WARNING  failed to import pomodoro from core: No module named 'modules.core.pomodoro'
[2022-11-25 00:44:12,159] module           DEBUG    importing pomodoro from contrib
[2022-11-25 00:44:12,159] input            DEBUG    registering callback pomodoro::left-mouse
[2022-11-25 00:44:12,159] input            DEBUG    registering callback pomodoro::right-mouse
[2022-11-25 00:44:12,159] module           WARNING  failed to import dunstctl from core: No module named 'modules.core.dunstctl'
[2022-11-25 00:44:12,160] module           DEBUG    importing dunstctl from contrib
[2022-11-25 00:44:12,160] input            DEBUG    registering callback dunstctl::left-mouse
[2022-11-25 00:44:12,262] module           DEBUG    importing pulseout from core
[2022-11-25 00:44:12,263] input            DEBUG    registering callback pulseout::left-mouse
[2022-11-25 00:44:12,263] input            DEBUG    registering callback pulseout::wheel-up
[2022-11-25 00:44:12,263] input            DEBUG    registering callback pulseout::wheel-down
[2022-11-25 00:44:12,263] cli              DEBUG    pulseaudio --start
[2022-11-25 00:44:33,124] input            DEBUG    registering callback ::wheel-up
[2022-11-25 00:44:33,125] input            DEBUG    registering callback ::wheel-down
[2022-11-25 00:44:33,128] module           DEBUG    importing debug from core
[2022-11-25 00:44:33,128] module           WARNING  failed to import spotify from core: No module named 'modules.core.spotify'
[2022-11-25 00:44:33,134] module           DEBUG    importing spotify from contrib
[2022-11-25 00:44:33,134] input            DEBUG    registering callback spotify::1::left-mouse
[2022-11-25 00:44:33,134] input            DEBUG    registering callback spotify::2::left-mouse
[2022-11-25 00:44:33,135] input            DEBUG    registering callback spotify::3::left-mouse
[2022-11-25 00:44:33,136] module           DEBUG    importing sensors2 from core
[2022-11-25 00:44:33,137] cli              DEBUG    sensors -u 
[2022-11-25 00:44:33,140] cli              DEBUG    coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 52.000
  temp1_max: 85.000
  temp1_crit: 105.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 50.000
  temp2_max: 85.000
  temp2_crit: 105.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 47.000
  temp3_max: 85.000
  temp3_crit: 105.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 47.000
  temp4_max: 85.000
  temp4_crit: 105.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 52.000
  temp5_max: 85.000
  temp5_crit: 105.000
  temp5_crit_alarm: 0.000

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 27.800
  temp1_crit: 106.000
temp2:
  temp2_input: 29.800
  temp2_crit: 106.000

amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:
  in0_input: 1.000
fan1:
  fan1_input: 581.000
  fan1_min: 0.000
  fan1_max: 3500.000
edge:
  temp1_input: 48.000
  temp1_crit: 94.000
  temp1_crit_hyst: -273.150
PPT:
  power1_average: 20.170
  power1_cap: 145.000


[2022-11-25 00:44:33,152] module           DEBUG    importing cpu from core
[2022-11-25 00:44:33,152] input            DEBUG    registering callback cpu::left-mouse
[2022-11-25 00:44:33,153] module           DEBUG    importing memory from core
[2022-11-25 00:44:33,153] input            DEBUG    registering callback memory::left-mouse
[2022-11-25 00:44:33,154] module           DEBUG    importing disk from core
[2022-11-25 00:44:33,154] input            DEBUG    registering callback disk::left-mouse
[2022-11-25 00:44:33,154] module           DEBUG    importing datetime from core
[2022-11-25 00:44:33,155] input            DEBUG    registering callback datetime::left-mouse
[2022-11-25 00:44:33,155] module           WARNING  failed to import arandr from core: No module named 'modules.core.arandr'
[2022-11-25 00:44:33,162] module           DEBUG    importing arandr from contrib
[2022-11-25 00:44:33,162] input            DEBUG    registering callback arandr::left-mouse
[2022-11-25 00:44:33,162] input            DEBUG    registering callback arandr::right-mouse
[2022-11-25 00:44:33,163] module           WARNING  failed to import pomodoro from core: No module named 'modules.core.pomodoro'
[2022-11-25 00:44:33,164] module           DEBUG    importing pomodoro from contrib
[2022-11-25 00:44:33,164] input            DEBUG    registering callback pomodoro::left-mouse
[2022-11-25 00:44:33,164] input            DEBUG    registering callback pomodoro::right-mouse
[2022-11-25 00:44:33,164] module           WARNING  failed to import dunstctl from core: No module named 'modules.core.dunstctl'
[2022-11-25 00:44:33,164] module           DEBUG    importing dunstctl from contrib
[2022-11-25 00:44:33,165] input            DEBUG    registering callback dunstctl::left-mouse
[2022-11-25 00:44:33,196] module           DEBUG    importing pulseout from core
[2022-11-25 00:44:33,196] input            DEBUG    registering callback pulseout::left-mouse
[2022-11-25 00:44:33,196] input            DEBUG    registering callback pulseout::wheel-up
[2022-11-25 00:44:33,196] input            DEBUG    registering callback pulseout::wheel-down
[2022-11-25 00:44:33,196] cli              DEBUG    pulseaudio --start
[2022-11-25 00:44:37,463] input            DEBUG    registering callback ::wheel-up
[2022-11-25 00:44:37,463] input            DEBUG    registering callback ::wheel-down
[2022-11-25 00:44:37,469] module           DEBUG    importing debug from core
[2022-11-25 00:44:37,469] module           WARNING  failed to import spotify from core: No module named 'modules.core.spotify'
[2022-11-25 00:44:37,475] module           DEBUG    importing spotify from contrib
[2022-11-25 00:44:37,476] input            DEBUG    registering callback spotify::1::left-mouse
[2022-11-25 00:44:37,476] input            DEBUG    registering callback spotify::2::left-mouse
[2022-11-25 00:44:37,476] input            DEBUG    registering callback spotify::3::left-mouse
[2022-11-25 00:44:37,478] module           DEBUG    importing sensors2 from core
[2022-11-25 00:44:37,478] cli              DEBUG    sensors -u 
[2022-11-25 00:44:37,495] cli              DEBUG    coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 53.000
  temp1_max: 85.000
  temp1_crit: 105.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 50.000
  temp2_max: 85.000
  temp2_crit: 105.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 49.000
  temp3_max: 85.000
  temp3_crit: 105.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 48.000
  temp4_max: 85.000
  temp4_crit: 105.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 53.000
  temp5_max: 85.000
  temp5_crit: 105.000
  temp5_crit_alarm: 0.000

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 27.800
  temp1_crit: 106.000
temp2:
  temp2_input: 29.800
  temp2_crit: 106.000

amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:
  in0_input: 1.000
fan1:
  fan1_input: 581.000
  fan1_min: 0.000
  fan1_max: 3500.000
edge:
  temp1_input: 48.000
  temp1_crit: 94.000
  temp1_crit_hyst: -273.150
PPT:
  power1_average: 20.036
  power1_cap: 145.000


[2022-11-25 00:44:37,508] module           DEBUG    importing cpu from core
[2022-11-25 00:44:37,508] input            DEBUG    registering callback cpu::left-mouse
[2022-11-25 00:44:37,509] module           DEBUG    importing memory from core
[2022-11-25 00:44:37,509] input            DEBUG    registering callback memory::left-mouse
[2022-11-25 00:44:37,510] module           DEBUG    importing disk from core
[2022-11-25 00:44:37,510] input            DEBUG    registering callback disk::left-mouse
[2022-11-25 00:44:37,511] module           DEBUG    importing datetime from core
[2022-11-25 00:44:37,511] input            DEBUG    registering callback datetime::left-mouse
[2022-11-25 00:44:37,511] module           WARNING  failed to import arandr from core: No module named 'modules.core.arandr'
[2022-11-25 00:44:37,518] module           DEBUG    importing arandr from contrib
[2022-11-25 00:44:37,519] input            DEBUG    registering callback arandr::left-mouse
[2022-11-25 00:44:37,519] input            DEBUG    registering callback arandr::right-mouse
[2022-11-25 00:44:37,519] module           WARNING  failed to import pomodoro from core: No module named 'modules.core.pomodoro'
[2022-11-25 00:44:37,520] module           DEBUG    importing pomodoro from contrib
[2022-11-25 00:44:37,520] input            DEBUG    registering callback pomodoro::left-mouse
[2022-11-25 00:44:37,520] input            DEBUG    registering callback pomodoro::right-mouse
[2022-11-25 00:44:37,520] module           WARNING  failed to import dunstctl from core: No module named 'modules.core.dunstctl'
[2022-11-25 00:44:37,521] module           DEBUG    importing dunstctl from contrib
[2022-11-25 00:44:37,521] input            DEBUG    registering callback dunstctl::left-mouse
[2022-11-25 00:44:37,550] module           DEBUG    importing pulseout from core
[2022-11-25 00:44:37,550] input            DEBUG    registering callback pulseout::left-mouse
[2022-11-25 00:44:37,550] input            DEBUG    registering callback pulseout::wheel-up
[2022-11-25 00:44:37,550] input            DEBUG    registering callback pulseout::wheel-down
[2022-11-25 00:44:37,550] cli              DEBUG    pulseaudio --start
```

**Comment by tobi-wan-kenobi** [comment]
Thanks for narrowing it down to a single module. Maybe it's some kind of concurrency issue between the pulseaudio server startup & the module. I will try to reproduce it (I use this on a daily basis and it works). Can you please let me know which distro you are using?

Also, I *still* am puzzled why the log shows no errors at all. Could you please try one more thing? Could you please try to "exec --no-startup-id <path-to-bumblebee-status> -m pulseout > /tmp/pulse.out 2> /tmp/pulse.err" inside your i3 config (so that I get the actual output on stdout and stderr)? And send me /tmp/pulse.out and /tmp/pulse.err?

That would be very helpful. Thank you!

**Comment by Dale-Muccignat** [comment]
I'm using straight archlinux... now that I'm thinking about it, could it be because I've installed pipewire?

Assuming you mean `exec --no-startup-id bumblebee-status -m pulseout > /tmp/pulse.out 2> /tmp/pulse.err` i get nothing in the pulse.err file but pulse.out gives:

```
{"version": 1, "click_events": true}
[
{"version":1}
[
[{"full_text": " pulseaudio --start not found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " pulseaudio --start not found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " pulseaudio --start not found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " pulseaudio --start not found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " pulseaudio --start not found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " pulseaudio --start not found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " pulseaudio --start not found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " pulseaudio --start not found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " pulseaudio --start not found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
```

Which.... makes me think I just am silly thinking I can use pipewire with a pulseaudo module.....

**Comment by Dale-Muccignat** [comment]
installing `pulseaudio` and removing `pipewire-pulse` resolved the issue... sorry for the big circle!

Is there a module that works with pipewire? I can see there's amixer but it doesn't seem as fleshed out. As far as I thought pipewire was supposed to be a drop-in replacement for pulseaudio... perhaps there's a way to make pulseout/pulsein compatable or a pipewire version if there's not one already? That's just me tossing out thoughts but I can work around this now.

Thanks so much for the help and I really love the work on bumblebee-status!

**Comment by tobi-wan-kenobi** [comment]
Glad that this is resolved!

I have a pipewire setup, and I believe the module works there. But I will investigate, thank you kindly!

**Comment by tobi-wan-kenobi** [comment]
Ah, and see: This is one of the errors:

```
{"version": 1, "click_events": true}
[
{"version":1}
```
Totally wrong format, thanks for catching that!

Aside from that, the `autostart` parameter doesn't work for pipewire (as there is no `pulseaudio`), but that should be handled nicer, IMHO.

Can you please try to get the stdout when `autostart` is not set? For me, on Gentoo, it works, but Gentoo arguably is different in its startup process (systemd vs. openrc).

**Comment by tobi-wan-kenobi** [comment]
Also, with the commit above, you should get a better error message in the status bar itself, if you use the -git package

**Comment by Dale-Muccignat** [comment]
I've installed the -git version from the AUR, removed autostart and put the debug command in the i3 config and now I get:

```
{"version": 1, "click_events": true}
[
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " list index out of range ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
```

The file fills up with the same line over time.

In the bar itself I now have:
![image](https://user-images.githubusercontent.com/14990150/204115010-94276a41-2d90-4a13-8900-1c9b7b5aa9c5.png)

Which seems a bit more informative!

**Comment by tobi-wan-kenobi** [comment]
Nice, so that helps a bit already.

I have pushed another change that logs all the debugs to the debug log (`-d -f <filename>`). Could you please add that once more to your execution & give me the results?

There should be a backtrace in it now, something like this:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

```

Hopefully, that narrows it down enough for me to fix it.

Thank you for your patience!

**Comment by Dale-Muccignat** [comment]
Here you go!

```
[2022-11-27 20:58:28,053] input            DEBUG    registering callback ::wheel-up
[2022-11-27 20:58:28,058] input            DEBUG    registering callback ::wheel-down
[2022-11-27 20:58:28,082] module           DEBUG    importing debug from core
[2022-11-27 20:58:28,082] module           WARNING  failed to import spotify from core: No module named 'modules.core.spotify'
[2022-11-27 20:58:28,094] module           DEBUG    importing spotify from contrib
[2022-11-27 20:58:28,095] input            DEBUG    registering callback spotify::1::left-mouse
[2022-11-27 20:58:28,095] input            DEBUG    registering callback spotify::2::left-mouse
[2022-11-27 20:58:28,095] input            DEBUG    registering callback spotify::3::left-mouse
[2022-11-27 20:58:28,096] module           DEBUG    importing sensors2 from core
[2022-11-27 20:58:28,096] cli              DEBUG    sensors -u 
[2022-11-27 20:58:28,115] cli              DEBUG    acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 27.800
  temp1_crit: 106.000
temp2:
  temp2_input: 29.800
  temp2_crit: 106.000

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 52.000
  temp1_max: 85.000
  temp1_crit: 105.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 50.000
  temp2_max: 85.000
  temp2_crit: 105.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 51.000
  temp3_max: 85.000
  temp3_crit: 105.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 50.000
  temp4_max: 85.000
  temp4_crit: 105.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 52.000
  temp5_max: 85.000
  temp5_crit: 105.000
  temp5_crit_alarm: 0.000

amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:
  in0_input: 1.037
fan1:
  fan1_input: 4.000
  fan1_min: 0.000
  fan1_max: 3500.000
edge:
  temp1_input: 47.000
  temp1_crit: 94.000
  temp1_crit_hyst: -273.150
PPT:
  power1_average: 18.205
  power1_cap: 145.000


[2022-11-27 20:58:28,133] module           DEBUG    importing cpu from core
[2022-11-27 20:58:28,134] input            DEBUG    registering callback cpu::left-mouse
[2022-11-27 20:58:28,134] module           DEBUG    importing memory from core
[2022-11-27 20:58:28,135] input            DEBUG    registering callback memory::left-mouse
[2022-11-27 20:58:28,135] module           DEBUG    importing disk from core
[2022-11-27 20:58:28,135] input            DEBUG    registering callback disk::left-mouse
[2022-11-27 20:58:28,136] module           DEBUG    importing datetime from core
[2022-11-27 20:58:28,136] input            DEBUG    registering callback datetime::left-mouse
[2022-11-27 20:58:28,261] module           DEBUG    importing pulseout from core
[2022-11-27 20:58:28,261] input            DEBUG    registering callback pulseout::left-mouse
[2022-11-27 20:58:28,262] input            DEBUG    registering callback pulseout::wheel-up
[2022-11-27 20:58:28,262] input            DEBUG    registering callback pulseout::wheel-down
[2022-11-27 20:58:28,397] bumblebee-status ERROR    list index out of range
Traceback (most recent call last):
  File "/home/dale/.config/i3/bumblebee-status/bumblebee-status", line 149, in <module>
    main()
  File "/home/dale/.config/i3/bumblebee-status/bumblebee-status", line 124, in main
    modules.append(core.module.load(module, config, theme))
  File "/home/dale/.config/i3/bumblebee-status/bumblebee_status/core/module.py", line 61, in load
    return getattr(mod, "Module")(config, theme)
  File "/home/dale/.config/i3/bumblebee-status/bumblebee_status/modules/core/pulseout.py", line 6, in __init__
    super().__init__(config, theme, "sink")
  File "/home/dale/.config/i3/bumblebee-status/bumblebee_status/modules/core/pulsectl.py", line 91, in __init__
    self.process(None)
  File "/home/dale/.config/i3/bumblebee-status/bumblebee_status/modules/core/pulsectl.py", line 141, in process
    dev = self.get_device(pulse)
  File "/home/dale/.config/i3/bumblebee-status/bumblebee_status/modules/core/pulsectl.py", line 135, in get_device
    return devs[0] # fallback
IndexError: list index out of range
```

Good luck!

**Comment by tobi-wan-kenobi** [comment]
@Dale-Muccignat Thanks!

I *think* that is sufficient to narrow it down - if you update to the latest git version (just updating the AUR package should be sufficient), I believe the error should be gone. You should see a volume of 0 for a moment, but then, it should be working correctly.

If not, please let me know & I will investigate further!

**Comment by Dale-Muccignat** [comment]
Thank you! Works like a charm now. It indeed displays 0 for maybe a second but then it kicks in nicely.
